# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_yuanshenqidong.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        Form.setMouseTracking(False)
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(260, 200, 111, 21))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(260, 230, 111, 21))
        self.b2.setObjectName("b2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(50, 50, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        self.b1.clicked.connect(lambda: self.textEdit.setText("元神启动！"))  # type: ignore
        self.b2.clicked.connect(lambda: self.textEdit.setText("星铁启动！"))  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "我是原神职业哥！"))
        self.b1.setText(_translate("Form", "你别说了"))
        self.b2.setText(_translate("Form", "你知道我要说什么"))

    def __init__(self):
        self.setupUi(MainWindow)
        self.setAcceptDrops(True)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()  # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_Form()  # ui是Ui_MainWindow()类的实例化对象
    MainWindow.show()  # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())  # 使用exit()或者点击关闭按钮退出QApplication
